# Generated by Django 4.0.5 on 2022-06-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=30, verbose_name='возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название курса')),
                ('info', models.TextField(blank=True, verbose_name='информация о курсе')),
                ('price_once_alone', models.IntegerField(default=600, verbose_name='цена за занятие без группы')),
                ('price_pass_alone', models.IntegerField(default=1600, verbose_name='цена за месяц без группы')),
                ('price_once_group', models.IntegerField(default=500, verbose_name='цена за занятие без группы')),
                ('price_pass_group', models.IntegerField(default=1400, verbose_name='цена за месяц без группы')),
                ('duration', models.IntegerField(default=60, verbose_name='длительность занятия')),
                ('count_a_week', models.IntegerField(default=1, verbose_name='занятий в неделю')),
                ('count_overall', models.IntegerField(default=10, verbose_name='занятий всего')),
                ('group_size', models.CharField(blank=True, max_length=30, verbose_name='размер группы')),
                ('age', models.ManyToManyField(to='mainapp.age', verbose_name='возраст')),
                ('subject', models.ManyToManyField(to='mainapp.subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.teacher', verbose_name='преподаватель')),
            ],
        ),
    ]
