# Generated by Django 4.0.5 on 2022-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_subject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50, verbose_name='Имя заказчика')),
                ('parent_surname', models.CharField(max_length=50, verbose_name='Фамилия заказчика')),
                ('parent_second_name', models.CharField(max_length=50, verbose_name='Отчество заказчика')),
                ('phone_pupil', models.IntegerField(verbose_name='Телефоно ученика')),
                ('e_mail_pupil', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('name_pupil', models.CharField(max_length=50, verbose_name='Имя ученика')),
                ('surname_pupil', models.CharField(max_length=50, verbose_name='Фамилия ученика')),
                ('second_name_pupil', models.CharField(max_length=50, verbose_name='Отчество ученика')),
                ('birthday_pupil', models.DateField(verbose_name='дата рождения ученика')),
                ('school', models.CharField(max_length=50, verbose_name='Место учебы')),
                ('phone_parent', models.IntegerField(null=True, verbose_name='Телефоно заказчика')),
                ('e_mail_parent', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта заказчика')),
                ('courses', models.ManyToManyField(to='mainapp.course')),
            ],
        ),
    ]
