# Generated by Django 4.0.5 on 2022-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_subject_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='parent_name',
            new_name='second_name',
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50, verbose_name='Имя заказчика')),
                ('parent_surname', models.CharField(max_length=50, verbose_name='Фамилия заказчика')),
                ('parent_second_name', models.CharField(max_length=50, verbose_name='Отчество заказчика')),
                ('phone_parent', models.CharField(max_length=12, verbose_name='Телефон заказчика')),
                ('e_mail_parent', models.EmailField(max_length=254, verbose_name='Электронная почта заказчика')),
                ('name_pupil', models.CharField(max_length=50, verbose_name='Имя ученика')),
                ('surname_pupil', models.CharField(max_length=50, verbose_name='Фамилия ученика')),
                ('second_name_pupil', models.CharField(max_length=50, verbose_name='Отчество ученика')),
                ('birthday_pupil', models.DateField(verbose_name='дата рождения ученика')),
                ('school_pupil', models.CharField(max_length=100, verbose_name='Место учебы')),
                ('phone_pupil', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон ученика')),
                ('e_mail_pupil', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта ученика')),
                ('subjects', models.ManyToManyField(to='mainapp.subject')),
            ],
        ),
    ]
