# Generated by Django 4.0.5 on 2022-06-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_parent_name_teacher_second_name_pupil'),
        ('mainapp', '0007_alter_course_subject'),
    ]

    operations = [
    ]
