# Generated by Django 4.0.5 on 2022-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_merge_20220627_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='subjects',
        ),
        migrations.AddField(
            model_name='pupil',
            name='courses',
            field=models.ManyToManyField(to='mainapp.course'),
        ),
    ]
