# Generated by Django 4.0.5 on 2022-06-29 17:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_pupil_subjects_pupil_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_url',
            field=tinymce.models.HTMLField(default='', verbose_name='ссылка на календарь'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='schedule_url',
            field=tinymce.models.HTMLField(default='', verbose_name='ссылка на расписание'),
        ),
    ]
