# Generated by Django 4.0.5 on 2022-07-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_sitesettings_calendar_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возрастная категория', 'verbose_name_plural': 'Возрастные категории'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курсы'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.teacher', verbose_name='преподаватель'),
        ),
    ]
