# Generated by Django 4.0.5 on 2022-07-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_age_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_email',
            field=models.EmailField(default='zarperspectiva@gmail.com', max_length=254, verbose_name='email администратора'),
        ),
    ]
