# Generated by Django 4.0.5 on 2022-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_sitesettings_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_once_group',
            field=models.IntegerField(default=500, verbose_name='цена за занятие в группе'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_pass_group',
            field=models.IntegerField(default=1400, verbose_name='цена за месяц в группе'),
        ),
    ]
