# Generated by Django 4.0.5 on 2022-07-03 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_course_price_once_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='sign_up_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата записи'),
            preserve_default=False,
        ),
    ]
