# Generated by Django 4.0.5 on 2022-07-04 17:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_pupil_sign_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='letter_template',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_letter_template',
            field=tinymce.models.HTMLField(default='Поступила новая заявка', verbose_name='шаблон письма администратору'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='client_letter_template',
            field=tinymce.models.HTMLField(default='Спасибо за заявку', verbose_name='шаблон письма клиенту'),
        ),
    ]
