# Generated by Django 4.0.5 on 2022-07-13 20:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_sitesettings_letter_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='age',
            field=models.ManyToManyField(related_name='ages', to='mainapp.age', verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=tinymce.models.HTMLField(blank=True, verbose_name='информация о курсе'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(related_name='subject', to='mainapp.subject', verbose_name='предмет'),
        ),
    ]
