# Generated by Django 4.0.5 on 2022-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_sitesettings_letter_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price_once_group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_pass_alone',
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True, default='Индивидуальные занятия возможны только при наличии возможности у педагога и при отсутствии групп. Про возможность индивидуальных занятий уточняйте у администратора центра (127.0.0.1/contacts/)\n                Стоимость индивидуальных занятий\n                45 минут – 2550 руб. абонемент 4 занятия/разовая оплата -750 руб.\n                60 минут - 3400 руб. абонемент 4 занятия/разовая оплата -1000 руб.\n                90 минут - 5100 руб. абонемент 4 занятия/разовая оплата -1500 руб.', verbose_name='информация о курсе'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_once_alone',
            field=models.IntegerField(default=600, verbose_name='Разовая оплата за занятие'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_pass_group',
            field=models.IntegerField(default=1400, verbose_name='Цена за месяц по абонементу'),
        ),
    ]
