# Generated by Django 4.0.5 on 2022-07-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_course_age_alter_course_info_and_more'),
        ('mainapp', '0017_remove_course_price_once_group_and_more'),
    ]

    operations = [
    ]
