# Generated by Django 4.0.5 on 2022-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_course_price_once_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='terms_conditions',
            field=models.TextField(default='', verbose_name='Политика конфиденциальности и обработки персональных данных'),
        ),
    ]
