# Generated by Django 4.0.5 on 2022-07-17 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_merge_20220717_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default='Индивидуальные занятия возможны только при наличии возможности у педагога и при отсутствии групп. Про возможность индивидуальных занятий уточняйте у администратора центра (127.0.0.1/contacts/)\n                Стоимость индивидуальных занятий\n                45 минут – 2550 руб. абонемент 4 занятия/разовая оплата -750 руб.\n                60 минут - 3400 руб. абонемент 4 занятия/разовая оплата -1000 руб.\n                90 минут - 5100 руб. абонемент 4 занятия/разовая оплата -1500 руб.', verbose_name='информация о курсе'),
        ),
    ]
