# Generated by Django 4.0.5 on 2022-07-18 05:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_course_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=45, verbose_name='длительность урока')),
                ('price_once', models.CharField(max_length=32, verbose_name='разовая оплата')),
                ('price_month', models.CharField(max_length=32, verbose_name='абонемент 4 занятия')),
            ],
            options={
                'verbose_name': 'академический час',
                'verbose_name_plural': 'академические часы',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='информация о курсе'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_hour', to='mainapp.academichour', verbose_name='длительность занятия'),
        ),
    ]
