# Generated by Django 4.0.5 on 2022-07-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_course_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=45, verbose_name='длительность урока')),
                ('price_once', models.IntegerField(verbose_name='разовая оплата')),
                ('price_month', models.IntegerField(verbose_name='абонемент 4 занятия')),
            ],
            options={
                'verbose_name': 'академический час',
                'verbose_name_plural': 'академические часы',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=tinymce.models.HTMLField(blank=True, default='Индивидуальные занятия возможны только при наличии возможности у педагога и при отсутствии групп. Про возможность индивидуальных занятий уточняйте у администратора центра (http://127.0.0.1:8000/contacts/)\n                Стоимость индивидуальных занятий\n                45 минут – 2550 руб. абонемент 4 занятия/разовая оплата -750 руб.\n                60 минут - 3400 руб. абонемент 4 занятия/разовая оплата -1000 руб.\n                90 минут - 5100 руб. абонемент 4 занятия/разовая оплата -1500 руб.', verbose_name='информация о курсе'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.academichour', verbose_name='длительность занятия'),
        ),
    ]
