# Generated by Django 4.0.5 on 2022-08-03 17:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_academichour_alter_course_info_course_academic_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='center_info',
            field=tinymce.models.HTMLField(default='', verbose_name='информация о центре'),
        ),
    ]
