# Generated by Django 4.0.5 on 2022-07-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_academichour_alter_course_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.academichour', verbose_name='длительность занятия'),
        ),
    ]
