# Generated by Django 4.0.5 on 2022-08-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_sitesettings_terms_conditions'),
        ('mainapp', '0020_academichour_alter_course_info_course_academic_hour'),
    ]

    operations = [
    ]
