# Generated by Django 4.0.5 on 2022-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='Аноним', max_length=300, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(default='Родитель', max_length=8, verbose_name='Роль'),
        ),
    ]
