# Generated by Django 4.0.5 on 2022-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_review_author_review_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(default='Родитель', max_length=20, verbose_name='Роль'),
        ),
    ]
