# Generated by Django 4.0.5 on 2022-08-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_pupil_student'),
        ('mainapp', '0021_sitesettings_center_info'),
        ('mainapp', '0024_alter_review_role'),
    ]

    operations = [
    ]
