# Generated by Django 4.0.5 on 2022-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_teacher_info_alter_review_role_alter_teacher_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='address_parent',
            field=models.CharField(default='не указан', max_length=256, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='comment',
            field=models.TextField(default='', max_length=256, verbose_name='комментарий'),
        ),
    ]
