# Generated by Django 4.0.5 on 2022-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_pupil_address_parent_pupil_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='комментарий'),
        ),
    ]
