# Generated by Django 4.0.5 on 2024-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_pupil_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='academichour',
            name='price_month_ind',
            field=models.CharField(default=2550, max_length=32, verbose_name='абонемент 4 занятия (индивидуально)'),
        ),
        migrations.AddField(
            model_name='academichour',
            name='price_once_ind',
            field=models.CharField(default=750, max_length=32, verbose_name='разовая оплата (индивидуально)'),
        ),
        migrations.AlterField(
            model_name='academichour',
            name='price_month',
            field=models.CharField(max_length=32, verbose_name='абонемент 4 занятия (групп)'),
        ),
        migrations.AlterField(
            model_name='academichour',
            name='price_once',
            field=models.CharField(max_length=32, verbose_name='разовая оплата (групп)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_once_alone',
            field=models.IntegerField(default=600, verbose_name='Разовая оплата за занятие (уст.)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_pass_group',
            field=models.IntegerField(default=1400, verbose_name='Цена за месяц по абонементу (уст.)'),
        ),
    ]
