# Generated by Django 4.0.5 on 2024-01-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_academichour_price_month_ind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='длительность занятия (уст.)'),
        ),
    ]
