# Generated by Django 4.0.5 on 2024-01-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_once_alone',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_pass_group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
    ]
