# Generated by Django 4.0.5 on 2024-01-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichour',
            options={'ordering': ['duration'], 'verbose_name': 'академический час', 'verbose_name_plural': 'академические часы'},
        ),
    ]
