# Generated by Django 4.0.5 on 2024-01-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_academichour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
