# Generated by Django 4.0.5 on 2024-01-13 03:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='г. Заречный, ул. Ленинградская, 29А', max_length=150, verbose_name='адрес центра'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_phone',
            field=models.CharField(default='+7-919-367-2831', max_length=50, verbose_name='телефон администратора'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='фото администратора'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_info',
            field=tinymce.models.HTMLField(default='На ваши вопросы всегда ответит администратор центра Ольга Валерьевна. Тел. +7-919-367-2831 (с 18 августа по 26 мая по будням с 15.00 до 20.00)', verbose_name='информация о контактах'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_link',
            field=models.CharField(default='https://vk.com/public.cpperspektiva', max_length=150, verbose_name='ссылка на ВК'),
        ),
    ]
