# Generated by Django 4.0.5 on 2022-07-05 17:32

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='ключ активации'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=authapp.models.default_key_expires, verbose_name='срок действия ключа активации'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='отчество'),
        ),
    ]
