# Generated by Django 4.0.5 on 2022-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_siteuser_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='почта подтверждена'),
        ),
    ]
