# Generated by Django 4.0.5 on 2022-07-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_siteuser_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'ученик', 'verbose_name_plural': 'ученики'},
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='родитель'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='отчество'),
        ),
    ]
