# Generated by Django 4.0.5 on 2022-07-28 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_student_options_remove_siteuser_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(default='000000000', max_length=12, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2010, 1, 1, 0, 0), verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='не указано', max_length=100, verbose_name='Место учебы'),
        ),
    ]
