# Generated by Django 4.0.5 on 2022-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_siteuser_phone_student_birthday_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='телефон'),
        ),
    ]
