# Generated by Django 4.0.5 on 2022-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_siteuser_first_name_alter_siteuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='address',
            field=models.CharField(default='не указан', max_length=256, verbose_name='адрес'),
        ),
    ]
