# Generated by Django 4.0.5 on 2022-08-08 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_siteuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='address',
            field=models.CharField(default='не указан', max_length=256, verbose_name='адрес заказчика'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта заказчика'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='имя заказчика'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='фамилия заказчика'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='отчество заказчика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2010, 1, 1, 0, 0), verbose_name='дата рождения ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='электронная почта ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='имя ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='фамилия ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, default='не указано', max_length=100, verbose_name='место учебы ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(max_length=150, verbose_name='отчество ученика'),
        ),
    ]
